# Generated by Django 3.1.1 on 2020-09-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_race', '0002_auto_20200914_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='player',
            name='modified_by',
        ),
    ]
