# Generated by Django 3.1.1 on 2020-09-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_race', '0006_auto_20200915_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='player',
        ),
    ]
