# Generated by Django 3.1.1 on 2020-09-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_race', '0007_remove_race_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
