# Generated by Django 3.1.1 on 2020-09-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_race', '0010_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heading',
            old_name='heading1',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='heading',
            name='heading2',
        ),
    ]
