# Generated by Django 3.1.1 on 2020-09-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_race', '0013_remove_player_current_race_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_idex_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
