# Generated by Django 3.1.1 on 2020-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_race', '0014_auto_20200918_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_idex_num',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_num',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_rating',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_weight',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
