# Generated by Django 3.1.1 on 2020-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_race', '0015_auto_20200918_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_weight',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
